"""Initial migration - User model

Revision ID: 93cc500fd6c3
Revises: 
Create Date: 2026-02-21 21:26:43.076719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cc500fd6c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('home_currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CNY', 'INR', 'CAD', 'AUD', 'CHF', 'SEK', 'NZD', 'SGD', 'HKD', 'NOK', 'KRW', 'MXN', 'BRL', 'ZAR', 'RUB', 'TRY', 'PLN', 'DKK', 'THB', 'IDR', 'MYR', 'PHP', 'CZK', 'HUF', 'ILS', 'CLP', 'AED', 'SAR', 'EGP', 'PKR', 'BDT', 'VND', 'NGN', 'KES', 'GHS', 'UAH', 'ARS', 'COP', 'PEN', 'RON', 'QAR', 'KWD', name='currencyenum'), nullable=False),
    sa.Column('study_country_currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CNY', 'INR', 'CAD', 'AUD', 'CHF', 'SEK', 'NZD', 'SGD', 'HKD', 'NOK', 'KRW', 'MXN', 'BRL', 'ZAR', 'RUB', 'TRY', 'PLN', 'DKK', 'THB', 'IDR', 'MYR', 'PHP', 'CZK', 'HUF', 'ILS', 'CLP', 'AED', 'SAR', 'EGP', 'PKR', 'BDT', 'VND', 'NGN', 'KES', 'GHS', 'UAH', 'ARS', 'COP', 'PEN', 'RON', 'QAR', 'KWD', name='currencyenum'), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_frequency', sa.Enum('WEEKLY', 'BI_WEEKLY', 'MONTHLY', 'SEMI_MONTHLY', 'IRREGULAR', 'NONE', name='incomefrequencyenum'), nullable=True),
    sa.Column('scholarship_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scholarship_frequency', sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'SEMESTER', 'ANNUAL', 'NONE', name='scholarshipfrequencyenum'), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('student_status', sa.Enum('UNDERGRADUATE', 'GRADUATE', 'MASTERS', 'PHD', 'POST_DOC', 'EXCHANGE', 'CERTIFICATE', name='studentstatusenum'), nullable=True),
    sa.Column('visa_type', sa.Enum('F1', 'J1', 'M1', 'H1B', 'OPT', 'CPT', 'B1_B2', 'CITIZEN', 'OTHER', 'NONE', name='visatypeenum'), nullable=True),
    sa.Column('max_work_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('total_loan_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_loan_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loan_start_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_active_verified', 'users', ['is_active', 'email_verified'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_active_verified', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
