"""add_forecast_context

Revision ID: d19eed081216
Revises: f408dc8065b8
Create Date: 2026-03-23 12:19:11.770634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19eed081216'
down_revision: Union[str, Sequence[str], None] = 'f408dc8065b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('is_summer_break', sa.Boolean(), nullable=False),
    sa.Column('is_winter_break', sa.Boolean(), nullable=False),
    sa.Column('travel_home', sa.Boolean(), nullable=False),
    sa.Column('tuition_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scholarship_received', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('health_insurance', sa.Boolean(), nullable=False),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_forecast_context_user_month')
    )
    op.create_index('ix_forecast_context_user_id', 'forecast_context', ['user_id'], unique=False)
    op.create_index('ix_forecast_context_user_year', 'forecast_context', ['user_id', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_context_user_year', table_name='forecast_context')
    op.drop_index('ix_forecast_context_user_id', table_name='forecast_context')
    op.drop_table('forecast_context')
    # ### end Alembic commands ###
