"""add_travel_cost_to_forecast_context

Revision ID: d7e54f925337
Revises: d19eed081216
Create Date: 2026-03-23 12:27:55.236575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e54f925337'
down_revision: Union[str, Sequence[str], None] = 'd19eed081216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_context', sa.Column('travel_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_context', 'travel_cost')
    # ### end Alembic commands ###
