"""add_recurring_generation_tracking

Revision ID: f408dc8065b8
Revises: 8de496c4c70a
Create Date: 2026-03-19 12:02:54.014103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f408dc8065b8'
down_revision: Union[str, Sequence[str], None] = '8de496c4c70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recurring_parent_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('is_generated', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_transactions_recurring_parent_id'), 'transactions', ['recurring_parent_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'transactions', ['recurring_parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_recurring_parent_id'), table_name='transactions')
    op.drop_column('transactions', 'is_generated')
    op.drop_column('transactions', 'recurring_parent_id')
    # ### end Alembic commands ###
